name: Test and dist

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write # This is required to create a release

concurrency:
  group: "test-and-dist"
  cancel-in-progress: true

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🚀 Setup
        uses: ./.github/actions/setup-node-pnpm

      - name: 🧹 Lint code
        run: pnpm all

      - name: 🧪 Run tests
        run: pnpm test

  dist:
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🚀 Setup
        uses: ./.github/actions/setup-node-pnpm

      # Setup git config to allow pushes
      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Build the distribution
        continue-on-error: true
        run: pnpm run dist
